"""Add tenants and registro_auditoria

Revision ID: 9369ce2c67fd
Revises: 001
Create Date: 2026-09-17 18:33:42.691660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9369ce2c67fd'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nombre_comercial', sa.String(length=255), nullable=False),
    sa.Column('razon_social', sa.String(length=255), nullable=False),
    sa.Column('ruc_identificacion', sa.String(length=50), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('tamano', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ruc_identificacion')
    )
    op.create_table('registro_auditoria',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('id_diagnostico', sa.String(length=100), nullable=False),
    sa.Column('normativa', sa.String(length=50), nullable=True),
    sa.Column('snapshot_hash', sa.String(length=255), nullable=False),
    sa.Column('fecha_certificacion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('derechos_arco_solicitudes')
    op.drop_table('transferencias_terceros')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transferencias_terceros',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tercero_nombre', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('pais_destino', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('nivel_adecuacion', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('fecha_registro', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('transferencias_terceros_pkey'))
    )
    op.create_table('derechos_arco_solicitudes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('titular_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('tipo_derecho', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('estado', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('derechos_arco_solicitudes_pkey'))
    )
    op.drop_table('registro_auditoria')
    op.drop_table('tenants')
    # ### end Alembic commands ###
