/**
 * Ejemplos breves de lectura para cada control del diagnóstico.
 * Son situaciones ilustrativas; no sustituyen el requisito ni constituyen evidencia.
 */
const EJEMPLOS: Record<number, string> = {
  1: "Es un documento corto que dice qué datos de personas maneja la organización y cómo los cuida. Por ejemplo, quien dirige la organización firma una hoja con esas reglas y se la entrega a todo el que trabaja allí.",
  2: "Alguien debe poder responder cuando hay dudas o problemas con los datos. Por ejemplo, quien dirige la organización, o la persona que él o ella elija, queda anotada como la encargada de este tema y el equipo sabe a quién preguntarle. En una organización pequeña puede ser el propio dueño.",
  3: "No todas las organizaciones están obligados a nombrar a este delegado; depende de cuántos datos y de qué tipo manejan. Por ejemplo, se deja una nota fechada que dice «revisamos la ley y concluimos que sí/no debemos nombrar delegado, por estas razones».",
  4: "El delegado debe poder advertir de un problema sin temor a represalias. Por ejemplo, puede avisar directamente a quien dirige la organización que falta proteger algo, y se anota qué se hará con su recomendación. Si la organización no tiene delegado, esta pregunta no aplica.",
  5: "Es una lista sencilla de lo que la ley pide y quién se encarga de cada punto. Por ejemplo, una tabla con dos columnas: «avisar a las personas cómo usamos sus datos» y el nombre de quien lo cumple.",
  6: "Puede ser una reunión corta entre las personas que toman decisiones en la organización. Por ejemplo, cada cierto tiempo se juntan, revisan los pendientes sobre datos personales y dejan escrito lo que acordaron.",
  7: "Sirve para que nadie use una versión vieja. Por ejemplo, los documentos sobre datos están en una misma carpeta (física o digital) y cada uno indica su fecha y quién lo aprobó.",
  8: "Medir ayuda a saber si se está mejorando. Por ejemplo, cada cierto tiempo se anota cuántas solicitudes de personas llegaron, cuántas se respondieron y cuántos problemas hubo, y se le muestra a quien dirige la organización.",
  9: "Es como un inventario, pero de datos. Por ejemplo, una lista que dice «ventas: se recogen nombre y teléfono del cliente y se guardan en un cuaderno o en Excel; nómina: se guardan datos de los empleados en tal archivo».",
  10: "El RAT es una tabla o formato donde se anota cada actividad con datos. Por ejemplo, una fila dice «pago de sueldos: se usan nombre, cédula y cuenta bancaria; para pagar; se guardan por el tiempo que exige la ley; se comparten con el banco».",
  11: "Los datos se piden con un propósito y no deben usarse para otro sin avisar. Por ejemplo, el correo que da un cliente se usa para enviarle su factura, y no para enviarle publicidad si no lo autorizó.",
  12: "La ley exige una razón válida para usar los datos de alguien. Por ejemplo: los datos del empleado se usan porque hay un contrato de trabajo; los del cliente para enviarle ofertas se usan porque él dio su permiso. Esa razón queda anotada.",
  13: "Son datos que, si se filtran, pueden causar mucho daño a la persona. Por ejemplo, si la organización guarda certificados médicos o huellas digitales, se identifican como sensibles y se guardan aparte, con acceso solo para quien los necesita.",
  14: "No conviene guardar datos para siempre. Por ejemplo, se decide que las hojas de vida de quienes no fueron contratados se destruyen a los seis meses, y se hace.",
  15: "Pedir de más es un riesgo. Por ejemplo, para hacer una factura se piden nombre, cédula y correo, pero no estado civil ni fecha de nacimiento; y si el cliente avisa que cambió de correo, se corrige.",
  16: "La lista de actividades con datos no sirve si queda desactualizada. Por ejemplo, al empezar a vender por internet o contratar a un proveedor nuevo, se agrega esa actividad a la lista, y se revisa completa al menos una vez al año.",
  17: "Es un texto que la persona puede leer antes de entregar sus datos. Por ejemplo, un cartel visible en el local, una hoja o una página web que dice «usamos tus datos para vender y facturar; si quieres corregirlos o borrarlos, escribe a este correo o pregunta aquí».",
  18: "La persona debe poder leer cómo se usarán sus datos antes de enviarlos. Por ejemplo, debajo de un formulario en línea hay un enlace «Aviso de privacidad».",
  19: "También hay que informar fuera de internet. Por ejemplo, un cartel a la vista en el lugar de atención, o una frase al pedir los datos: «los usaremos para este trámite».",
  20: "Se trata de evitar lenguaje legal difícil. Por ejemplo, en lugar de «tratamiento de datos para fines comerciales», el aviso dice «usaremos tu correo para enviarte ofertas».",
  21: "El permiso debe ser voluntario, claro y comprobable. Por ejemplo, una casilla sin marcar que dice «Acepto recibir ofertas», o una firma en una hoja, y se guarda constancia de cuándo lo dio.",
  22: "Quien dio su permiso puede cambiar de opinión. Por ejemplo, cada mensaje de ofertas indica cómo dejar de recibirlas (un enlace o un número al cual avisar) y, cuando la persona lo hace, ya no se le escribe más.",
  23: "Las personas tienen derecho a pedir ver, corregir o borrar sus datos. Por ejemplo, una hoja que dice «si alguien pide ver sus datos, se anota la solicitud y esta persona responde en tal plazo».",
  24: "Debe ser fácil para la persona saber cómo hacer su solicitud. Por ejemplo, un correo, un teléfono o un buzón publicado en el local o en la página, sin costo para quien lo usa.",
  25: "Sirve como prueba de que se atendió a la persona. Por ejemplo, un cuaderno o una hoja de Excel con una fila por cada solicitud: fecha, qué pidió, qué se respondió y cuándo se cerró.",
  26: "La ley da un tiempo límite para responder. Por ejemplo, llegó una solicitud el día 1 y se respondió antes del día 15.",
  27: "La persona debe entender la respuesta. Por ejemplo, «No podemos borrar su factura porque la ley nos obliga a conservarla durante cierto tiempo», dicho con palabras sencillas.",
  28: "Evita que un desconocido obtenga datos de otra persona. Por ejemplo, antes de entregar o cambiar algo, se pide la cédula o se confirma desde el correo o teléfono que ya estaban registrados.",
  29: "A veces otra persona pide en nombre del dueño de los datos. Por ejemplo, un abogado pide los datos de un empleado: antes de entregarlos se verifica y guarda el poder o documento que demuestre que lo representa. Aunque rara vez ocurra, conviene tener claro qué hacer.",
  30: "Si la persona no queda conforme, puede acudir a la autoridad. Por ejemplo, al responder una solicitud se le comenta que puede reclamar ante la Superintendencia, y se sabe quién atendería un pedido de esa entidad.",
  31: "Se llama portabilidad. Por ejemplo, un cliente pide sus datos y se le entrega un archivo común (Excel o PDF) para que pueda llevarlos a otra organización.",
  32: "Es un ensayo para comprobar que se sabría qué hacer. Por ejemplo, se imagina que un cliente pide borrar sus datos y se revisa si el equipo sabría a quién avisar, dónde borrar y en cuántos días responder.",
  33: "Al empezar la relación con una persona, se le explica el uso de sus datos y se le piden solo los necesarios. Por ejemplo, al inscribir a un cliente se piden nombre y teléfono y se le dice «los usaremos para avisarle de su pedido».",
  34: "Si un dato cambia, debe corregirse en todos los sitios donde está guardado. Por ejemplo, si un cliente cambia de teléfono, se corrige en el cuaderno, en el Excel y en el celular donde lo tenían anotado.",
  35: "Las cookies son pequeños archivos que siguen lo que hace una persona en una página. Por ejemplo, al entrar a la página aparece un mensaje que pregunta si se aceptan cookies de publicidad.",
  36: "Quien no quiere recibir publicidad debe poder decirlo fácilmente. Por ejemplo, las ofertas se envían solo a quienes aceptaron, y cada mensaje explica cómo dejar de recibirlas.",
  37: "Los datos de empleados son privados. Por ejemplo, las hojas de vida, certificados médicos y cuentas bancarias se guardan bajo llave o con clave, y solo las ve quien las necesita para temas laborales.",
  38: "Si hay cámaras, las personas deben saberlo y las grabaciones deben protegerse. Por ejemplo, un letrero «Zona videovigilada» en la entrada, grabaciones que se borran pasado un tiempo definido, y solo quien dirige la organización puede revisarlas.",
  39: "Cuando ya no hacen falta, los datos se eliminan. Por ejemplo, al terminar la relación con un cliente y pasar el plazo que exige la ley, se borran sus datos del sistema y de los archivos.",
  40: "Anonimizar es quitar los datos que identifican a la persona. Por ejemplo, un informe de ventas muestra «Cliente 1048» en lugar de nombre y cédula.",
  41: "Un proveedor es cualquier tercero que ve o recibe datos. Por ejemplo, la lista incluye al contador, al servicio de internet o nube, y al servicio de entregas, con lo que hace cada uno.",
  42: "Antes de dar datos a un tercero, conviene saber si los protege. Por ejemplo, se le pregunta cómo guarda la información, quién puede verla y qué hace si hay un problema.",
  43: "Lo acordado debe estar por escrito. Por ejemplo, el contrato o acuerdo dice que el proveedor usará los datos solo para el servicio contratado, los mantendrá en reserva y los protegerá.",
  44: "El proveedor no debe pasar los datos a otra organización sin permiso. Por ejemplo, el contrato dice que, si necesita contratar a otra organización, debe pedir autorización por escrito y exigirle lo mismo.",
  45: "Se trata de saber dónde están realmente los datos. Por ejemplo, se sabe que las copias están en un servicio de internet como Google Drive y en qué país tiene sus servidores.",
  46: "Enviar datos a otro país exige cuidados adicionales. Por ejemplo, la organización usa un servicio cuyos servidores están en otro país, lo tiene anotado y verificó que protege los datos o firmó un acuerdo que lo exige.",
  47: "Un técnico externo no debe ver más de lo necesario. Por ejemplo, se le da acceso solo al equipo que repara, solo por el tiempo de la visita, y se anota qué hizo. Aunque rara vez ocurra, conviene tener claro qué se haría.",
  48: "Al terminar la relación con un proveedor, los datos no deben quedarse con él. Por ejemplo, se le pide que los devuelva o los borre, que lo confirme por escrito y se le quitan sus accesos.",
  49: "Evita que se mezcle quién hizo qué. Por ejemplo, cada persona tiene su propio usuario y clave, no los comparte, y cuando deja de trabajar en la organización se cancela su acceso.",
  50: "Es una verificación en dos pasos. Por ejemplo, además de la clave del correo, llega un código al celular que hay que ingresar para entrar.",
  51: "El cifrado es un código secreto que impide leer la información si alguien la roba. Por ejemplo, la página de la organización muestra el candado (https) y los computadores o celulares con datos tienen activada la protección del disco.",
  52: "Sirve para saber quién consultó o cambió información. Por ejemplo, el sistema, o una hoja de control, permite ver «tal persona abrió tal archivo en tal fecha». También sirve en papel: por ejemplo, una hoja donde se firma quién retira o consulta un expediente.",
  53: "Una copia de respaldo sirve si se pierde la información original. Por ejemplo, se copian los archivos periódicamente a un disco o a un servicio en internet, y de vez en cuando se recupera un archivo de prueba para confirmar que funciona.",
  54: "Las actualizaciones corrigen fallas que aprovechan los delincuentes. Por ejemplo, las actualizaciones automáticas están activadas y el antivirus está vigente en los equipos que guardan datos.",
  55: "Las pruebas no deben hacerse con datos reales. Por ejemplo, para probar un programa se usan clientes inventados.",
  56: "Los papeles y equipos con datos deben estar protegidos. Por ejemplo, las carpetas de clientes están en un mueble con llave y el local se cierra al salir.",
  57: "Todos deben saber qué hacer si algo sale mal. Por ejemplo, una hoja dice «si se pierde un celular o computador con datos, o ves algo sospechoso, avisa de inmediato a esta persona».",
  58: "Anotar lo ocurrido ayuda a no repetirlo. Por ejemplo, una hoja con «fecha: se perdió un computador portátil con datos de clientes; se cambiaron las claves».",
  59: "No todos los problemas son igual de graves. Por ejemplo, se filtraron datos de salud de varias personas (grave), frente a un correo enviado por error a una sola persona (leve).",
  60: "En ciertos casos la ley obliga a avisar a la autoridad. Por ejemplo, hay una hoja que dice «si se filtran datos que pueden perjudicar a las personas, se avisa a la Superintendencia en el plazo de la ley, y lo hace esta persona».",
  61: "Hay que frenar el problema sin destruir las pruebas. Por ejemplo, se bloquea la cuenta robada o se desconecta el equipo, y se guarda el mensaje sospechoso para revisarlo después.",
  62: "Las personas afectadas tienen derecho a saberlo. Por ejemplo, se les envía un mensaje: «se filtró su correo; no abra enlaces sospechosos y cambie su clave».",
  63: "Es un simulacro, como el de incendios. Por ejemplo, el equipo se reúne y practica «se perdió un computador con datos, ¿qué hacemos?» para ver si todos saben su papel.",
  64: "Después de resolver un problema, se aprende de él. Por ejemplo, tras un correo falso que engañó a alguien, se explica al equipo cómo reconocerlos.",
  65: "Es pensar qué podría salir mal para las personas. Por ejemplo, una tabla sencilla con «filtración de datos de clientes: probabilidad media, gravedad alta; qué hacemos para evitarlo».",
  66: "La Evaluación de Impacto es un análisis de qué riesgos corren las personas con una actividad nueva. Por ejemplo, antes de lanzar algo que guarde datos de salud, se revisa si hace falta hacer esa evaluación.",
  67: "Cuando una actividad es de riesgo alto, el análisis debe estar hecho. Por ejemplo, un documento corto explica qué datos se usan, qué podría salir mal y cómo se previene.",
  68: "El interés legítimo es una razón propia de la organización para usar datos, sin pedir permiso. Por ejemplo, se anota «usamos el correo de clientes actuales para avisarles de un producto similar; es razonable y no les perjudica». Si la organización nunca usa esa razón, no aplica.",
  69: "Se trata de pensar en la protección de datos desde el inicio, no después. Por ejemplo, al preparar algo nuevo (un formulario, una venta en línea, un sistema), se decide primero qué datos son realmente necesarios.",
  70: "La opción más protectora debe venir elegida desde el principio. Por ejemplo, la casilla «quiero recibir publicidad» aparece desmarcada y la persona decide si la marca.",
  71: "Algunos riesgos no se eliminan del todo. Por ejemplo, quien dirige la organización lee el riesgo que queda, decide si lo acepta y lo deja anotado y firmado.",
  72: "Es cuando un programa decide solo, sin que una persona revise. Por ejemplo, un sistema aprueba o rechaza créditos automáticamente y los clientes saben que existe esa evaluación.",
  73: "Quien maneja datos debe saber cómo cuidarlos. Por ejemplo, una charla al año, presencial o en video, sobre qué datos no compartir y cómo guardarlos.",
  74: "Los recordatorios ayudan a no olvidarlo. Por ejemplo, un mensaje periódico por correo o WhatsApp, o un cartel que dice «no compartas tus claves».",
  75: "Se trata de comprobar que se aprendió. Por ejemplo, después de la charla se hace un cuestionario corto o se pregunta qué haría cada uno si pasara algo.",
  76: "Es un calendario de revisiones. Por ejemplo, «en un mes se revisan los accesos a los sistemas; en otro, los contratos con proveedores», con el nombre de quien lo hará.",
  77: "Una auditoría es una revisión ordenada de cómo se cumple lo planeado. Por ejemplo, se revisan unos cuantos expedientes tomados al azar y se escribe un informe con lo encontrado.",
  78: "Lo encontrado debe quedar en un solo lugar. Por ejemplo, una tabla con cada problema, qué tan grave es, por qué ocurrió y quién lo corrige.",
  79: "Corregir no basta; hay que comprobar que funcionó. Por ejemplo, cada cierto tiempo se revisa la lista de correcciones pendientes y se confirma que las terminadas realmente resolvieron el problema.",
  80: "Quien dirige la organización debe revisar cómo va todo y decidir mejoras. Por ejemplo, una vez al año revisa los problemas ocurridos y los cambios en la ley, y anota qué mejoras se harán.",
  101: "En el estado de resultados, ventas y gastos financieros aparecen en categorías distintas.",
  102: "El estado de resultados muestra una fila llamada «Resultado Operativo».",
  103: "El informe muestra el subtotal previo a financiación e impuestos.",
  104: "Un gasto que no es inversión, financiación ni impuesto se clasifica como operativo.",
  105: "Una medida propia presentada a inversionistas se reconcilia con cifras auditadas.",
  106: "La organización explica por qué usa una medida propia y con qué subtotal IFRS se compara.",
};

export function ejemploDePregunta(id: number, evidenciaEsperada: string): string {
  return EJEMPLOS[id] ?? `Un caso concreto sería contar con: ${evidenciaEsperada}.`;
}
