/**
 * Ejemplos breves de lectura para cada control del diagnóstico.
 * Son situaciones ilustrativas; no sustituyen el requisito ni constituyen evidencia.
 */
const EJEMPLOS: Record<number, string> = {
  1: "La empresa entrega a su equipo una política de privacidad aprobada y vigente.",
  2: "Una persona tiene asignado por escrito quién decide y quién responde por los datos.",
  3: "La empresa documenta si necesita un delegado de protección de datos y por qué.",
  4: "El delegado puede informar un problema a la dirección sin pedir permiso al área evaluada.",
  5: "Una lista indica qué obligaciones de privacidad aplican a cada actividad de la empresa.",
  6: "Un grupo de responsables revisa periódicamente los asuntos de privacidad y deja actas.",
  7: "Las políticas tienen versión, fecha, responsable y un lugar común donde consultarlas.",
  8: "La dirección recibe un informe trimestral sobre incidentes y solicitudes de titulares.",
  9: "La empresa anota qué datos de clientes recoge, para qué y quién los usa.",
  10: "El RAT registra el tratamiento de datos de empleados, su finalidad y responsable.",
  11: "El formulario de clientes indica que el correo se usará para enviar la factura.",
  12: "La empresa registra la base que justifica usar los datos de cada proceso.",
  13: "Los datos de salud se identifican aparte y se protegen con medidas reforzadas.",
  14: "Las hojas de vida se eliminan al vencer el plazo de conservación definido.",
  15: "Para entregar una factura se pide solo la información realmente necesaria.",
  16: "Al abrir una tienda en línea, se actualiza el RAT con ese nuevo tratamiento.",
  17: "El aviso de privacidad vigente explica qué datos se recogen y cómo ejercer derechos.",
  18: "Antes de enviar un formulario web, la persona puede leer el aviso de privacidad.",
  19: "En recepción se informa al visitante sobre el uso de sus datos y cámaras.",
  20: "El aviso dice «usaremos tu correo para responderte» en lugar de jerga jurídica.",
  21: "Una casilla voluntaria registra si el cliente acepta recibir publicidad.",
  22: "El cliente retira su permiso para publicidad y el sistema deja de enviársela.",
  23: "Una guía indica quién recibe y responde una solicitud de acceso a datos.",
  24: "La web muestra un correo donde las personas pueden pedir acceso o corrección.",
  25: "Cada solicitud se anota con fecha de entrada, responsable y respuesta enviada.",
  26: "Una alerta avisa al responsable antes de vencer el plazo para responder.",
  27: "La respuesta explica por qué se aceptó o negó la petición de una persona.",
  28: "Antes de entregar datos, se comprueba que quien los pide es el titular.",
  29: "Si responde un apoderado, se revisa su autorización antes de entregar datos.",
  30: "El equipo sabe cuándo informar al titular sobre la posibilidad de acudir a la autoridad.",
  31: "Si procede, se entrega al titular un archivo reutilizable con sus datos.",
  32: "El equipo ensaya una solicitud ficticia y comprueba si puede responderla.",
  33: "Al registrar un cliente nuevo, se vincula correctamente su identidad y consentimiento.",
  34: "Cuando cambia la dirección de un cliente, se actualiza en los sistemas pertinentes.",
  35: "La app informa para qué pide ubicación antes de activar ese permiso.",
  36: "Una campaña de correo usa solo contactos que pueden recibir esa comunicación.",
  37: "Solo personal autorizado consulta expedientes y datos salariales de empleados.",
  38: "Un cartel informa sobre las cámaras y se limita quién ve las grabaciones.",
  39: "Al terminar un contrato, los datos se borran o bloquean según el plazo aplicable.",
  40: "Un informe estadístico reemplaza nombres por códigos para reducir identificación.",
  41: "La empresa mantiene una lista de proveedores que acceden a datos personales.",
  42: "Antes de contratar una nube, se revisan sus medidas de seguridad y privacidad.",
  43: "El contrato con el proveedor indica qué datos trata y qué debe hacer al terminar.",
  44: "Un proveedor pide autorización antes de encargar los datos a otra empresa.",
  45: "La empresa sabe en qué país se guardan las copias de su sistema en la nube.",
  46: "Antes de enviar datos a otro país, se documentan la finalidad y las garantías.",
  47: "El soporte externo recibe acceso temporal solo al sistema que debe reparar.",
  48: "Al terminar un contrato, el proveedor devuelve o elimina los datos y lo confirma.",
  49: "Cada empleado tiene su propia cuenta y acceso solo a lo que necesita.",
  50: "Para entrar al sistema se pide contraseña y un código de segundo factor.",
  51: "Los archivos sensibles viajan cifrados y se guardan cifrados en el servidor.",
  52: "El sistema registra quién consultó un expediente y cuándo lo hizo.",
  53: "Se restaura una copia de seguridad de prueba para comprobar que funciona.",
  54: "Se aplican parches de seguridad después de evaluar fallas detectadas.",
  55: "Los datos reales de clientes no se usan libremente en el entorno de pruebas.",
  56: "El archivo físico con expedientes solo se abre a personal autorizado.",
  57: "Una guía indica a quién avisar y qué hacer si se filtran datos.",
  58: "Cada incidente queda anotado con fecha, impacto, acciones y responsables.",
  59: "Una filtración de datos sensibles se clasifica como más grave que un correo erróneo sin datos.",
  60: "El equipo evalúa si una filtración debe notificarse a la autoridad y lo documenta.",
  61: "Al detectar un acceso indebido, se bloquea la cuenta y se conservan los registros.",
  62: "Si corresponde informar a los afectados, se prepara un mensaje claro sobre el incidente.",
  63: "El equipo simula una filtración y practica sus pasos de respuesta.",
  64: "Tras un incidente, se documenta la causa y se cambia el control que falló.",
  65: "La empresa califica los riesgos según probabilidad e impacto con el mismo criterio.",
  66: "Antes de usar datos sensibles a gran escala, se verifica si requiere una EIPD.",
  67: "La evaluación de impacto se completa y aprueba antes de iniciar el proyecto.",
  68: "Antes de usar interés legítimo, se compara el beneficio empresarial con los derechos de la persona.",
  69: "Al diseñar una app nueva, se decide desde el inicio qué datos son necesarios.",
  70: "La app inicia con la opción de compartir datos desactivada.",
  71: "Si persiste un riesgo alto, la dirección decide y registra cómo tratarlo.",
  72: "Si un algoritmo rechaza solicitudes, se revisa su efecto en las personas.",
  73: "Cada año se capacita al personal sobre cómo manejar datos de clientes.",
  74: "Un recordatorio breve enseña a reconocer correos falsos que piden contraseñas.",
  75: "Después del taller se comprueba si el personal sabe reportar una filtración.",
  76: "Existe un calendario para revisar internamente el sistema de privacidad.",
  77: "Una auditoría revisa expedientes, entrevista responsables y registra resultados.",
  78: "Cada incumplimiento detectado se anota con causa, responsable y plazo de corrección.",
  79: "Se comprueba que la corrección prometida realmente funciona.",
  80: "La dirección revisa los resultados y aprueba mejoras para el siguiente periodo.",
  101: "En el estado de resultados, ventas y gastos financieros aparecen en categorías distintas.",
  102: "El estado de resultados muestra una fila llamada «Resultado Operativo».",
  103: "El informe muestra el subtotal previo a financiación e impuestos.",
  104: "Un gasto que no es inversión, financiación ni impuesto se clasifica como operativo.",
  105: "Una medida propia presentada a inversionistas se reconcilia con cifras auditadas.",
  106: "La empresa explica por qué usa una medida propia y con qué subtotal IFRS se compara.",
};

export function ejemploDePregunta(id: number, evidenciaEsperada: string): string {
  return EJEMPLOS[id] ?? `Un caso concreto sería contar con: ${evidenciaEsperada}.`;
}
